--- 
document: 
  description: |
    Documentazione tecnica e operativa per il modello di sito e servizi per i Comuni, basato sul design system di Designers Italia..    
  name: "Modello Comuni"
  tags: 
    - siti web
    - design
    - comuni 
